pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                echo '🔨 Building Docker Image...'
                sh 'docker-compose build'
            }
        }

        stage('Stop Old Containers') {
            steps {
                echo '🛑 Stopping old containers...'
                sh 'docker-compose down'
            }
        }

        stage('Start Containers') {
            steps {
                echo '🚀 Starting containers...'
                sh 'docker-compose up -d'
            }
        }
    }
}
